apiVersion: v1
kind: Secret
metadata:
  name: neo4j-secrets
  namespace: dataforge
type: Opaque
stringData:
  username: "neo4j"
  password: "REPLACE_WITH_YOUR_NEO4J_PASSWORD"
  auth: "neo4j/REPLACE_WITH_YOUR_NEO4J_PASSWORD"
