apiVersion: v1
kind: Service
metadata:
  name: dataforge-storytelling
  labels:
    app: dataforge-storytelling
    component: accelerator
spec:
  type: ClusterIP
  ports:
  - port: 8007
    targetPort: 8007
    protocol: TCP
    name: http
  selector:
    app: dataforge-storytelling
---
apiVersion: v1
kind: Service
metadata:
  name: dataforge-storytelling-lb
  labels:
    app: dataforge-storytelling
    component: accelerator
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8007
    protocol: TCP
    name: http
  selector:
    app: dataforge-storytelling
